### ISSUE TITLE
ARIA .visuallyhidden elements are visible

### ISSUE THREAD

**Issue by futpib** [corejavascript/typeahead.js#106]
typeahead.js contains no CSS code that could be used to hide `.visuallyhidden` elements, these elements should either be hidden with inline `style="..."` or typeahead.js should include a CSS file one can include to hide ARIA elements introduces by #104

**Comment by jlbooker** [comment]
It would be nice to keep the styles inline, so there's nothing else needed to get a typeahead instance up and running.

However, I've long thought that we should include a basic sample CSS file. One of my first challenges when I first started using the original Twitter version was the last of any example CSS. With enough Googling around on StackOverflow, you can discover a few examples that tell you what the class names should be (but even that wasn't well documented at the time).

It really already requires a separate CSS file to get a typeahead instance working (and looking presentable). Since that's the case, we might as well go ahead and provide a basic reference CSS file with the `.visuallyhidden` style included too.

Other thoughts?
