### ISSUE TITLE
Add `.typeahead('update')` method to reload a dataset

### ISSUE THREAD

**Issue by 907th** [corejavascript/typeahead.js#143]
Add `.typeahead('update')` method to reload a dataset.

Typeahead calls `Dataset.update` only when new entered text is different from the text already put into input, but sometimes datasource depends on dynamic attributes which can change even if input text is not changed.

To avoid this limitation I had to use a hack:
```
  var resetAccountAutocompletion = function() {
    var oldVal = $accountNumber.val();
    $accountNumber.typeahead("val", "SomERandDomStrInG61792374876");
    $accountNumber.typeahead("val", oldVal);
  };
```

**Comment by cbrown06** [comment]
Hello,

I have a similar issue and have had to resort to a workaround. In my case, I've got two typeaheads "A" and "B", and when "A" changes, I need to clear "B", so I use .typeahead('val', '').  That clears the input, but until I type a non-whitespace character, the old drop-down is still displayed and the data source isn't queried.

I've set "minLength" to zero for typeahead "B", which is probably why the optimization in the internal typeahead "_setQuery" function is skipping the call that updates the dataset.  I'd suggest adapting the whitespace test when minLength is 0 but I don't know the code well enough to submit a patch, sorry.

**Comment by bryanrasmussen** [comment]
I believe this is a duplicate of https://github.com/corejavascript/typeahead.js/issues/132 ?

there is a pull request with the functionality that should work (linked in the issue) - maybe check out and see if that fixes your problem. I guess that pull request hasn't been accepted because it fails the test that was written to make sure that autocompletion does not happen when your new value is the same as your old value. :)

**Comment by 907th** [comment]
I'm closing stale issue.
