### ISSUE TITLE
How to include Bloodhound? Uncaught ReferenceError: Bloodhound is not defined

### ISSUE THREAD

**Issue by simplenotezy** [corejavascript/typeahead.js#204]
I am trying to use Bloodhound for my typeahead instance, but I am getting the following error:

    Uncaught ReferenceError: Bloodhound is not defined

This is my code:

		import 'corejs-typeahead/dist/typeahead.bundle.min.js';
		var results = new Bloodhound({
			datumTokenizer: Bloodhound.tokenizers.obj.whitespace('value'),
			queryTokenizer: Bloodhound.tokenizers.whitespace,
			prefetch: source + '&prefetch&uri=' + current_uri,
			remote: {
				url: source + '&remote&uri=' + current_uri + '&q=%QUERY',
				wildcard: '%QUERY'
			}
		});

What am I doing wrong?

**Comment by simplenotezy** [comment]
I have also tried

    require("corejs-typeahead/dist/typeahead.bundle");

**Comment by jlbooker** [comment]
The `dist/typeahead.bundle.min.js` is a jQuery module and wasn't built with `import` or `require` in mind.

Try just including it via a `<script>` tag in the page's html.

**Comment by simplenotezy** [comment]
Hey @jlbooker,
I will do that. I just wish there was a more convenient way to include it.
Let me know if you know any other solution - thanks for your answer! 😊

**Comment by xf039** [comment]
@jlbooker Injecting script tags is not a solution.

Why are you closing this issue instead of of marking it as bug or feature request?
Issues should be worked on not just tossed away; if there is no plan to further improve this project why still bother to spend effort on it / keep the repo online?

**Comment by xf039** [comment]
@simplenotezy I don't know if they have fixed the problem by now but I'm able to use it using require js:

`window.Bloodhound = require('corejs-typeahead/dist/bloodhound.min')`

**Comment by jlbooker** [comment]
@xf039 Injecting script tags is the intended method of using this jQuery plugin. Compatibility with other bundling methods (Webpack, Browserify, etc) was never a goal of the project, as that's not typically how jQuery plugins are used. If someone wants to do the work to support those, that's fine by me. However, this was issue was opened as a question about resolving an error, to which I provided a method of resolving said error. It was not opened as a feature request to support usage via `require()`, which again is likely beyond the original scope of the project. I'm not against further improvements, but have no time to work on them myself. I keep this repo online in order to benefit those who do still use this plug-in and need occasional minor updates.
