### ISSUE TITLE
Confusing name (Typeahead.js or corejs-typeahead?)

### ISSUE THREAD

**Issue by Chealer** [corejavascript/typeahead.js#245]
This project mostly refers to itself as _Typeahead.js_. Yet:

1. [The _readme_ file](https://github.com/corejavascript/typeahead.js/blob/master/readme.md)'s title is _corejs-typeahead_.
2. There is [a different project also called _Typeahead.js_](https://github.com/twitter/typeahead.js), on which this one is based.

It would help a lot to explicitly indicate what this project's name is.

**Comment by jlbooker** [comment]
You should take the readme file's title as the name of this project.

The project was forked from Twitter's typeahead.js project after that project was abandoned. You'll still find references to twitter's Typeahead.js name due to the fork. It wasn't necessary to go through and update all those references. They're essentially the same code base anyways, with this repo having a few critical bug fixes and some basic improvements.

**Comment by Chealer** [comment]
Thanks @jlbooker but this is an issue report, not a question. What I meant is that pending a proper solution, the readme file should explicitly indicate what this project's name is.

**Comment by jlbooker** [comment]
I believe the readme file already correctly indicates the project name.

**Comment by Chealer** [comment]
The readme file does correctly implicitly indicate the project name. It _**also** incorrectly_ implicitly indicate the project name.

To be perfectly clear, to solve this in an acceptable manner, either:

1. the project should stop using the incorrect name
2. or, at least, the readme file should **explicitly** indicate the project name

**Comment by Chealer** [comment]
@jlbooker can you please reopen this ticket?
