### ISSUE TITLE
Release v1.0.0

### ISSUE THREAD

**Issue by mwjackson** [corejavascript/typeahead.js#55]
milestone:v0.11.2 

are these issues still valid to push out a release?

**Comment by mikemad** [comment]
Please release!!

**Comment by sheeley** [comment]
Yes, I believe they are.

**Comment by p2bauer** [comment]
This release would be great to get up to bower!

**Comment by carlosagsmendes** [comment]
Hi, are the referenced issues blocking to creating a new release? Thanks in advance

**Comment by jonchay** [comment]
Any reason why this isn't released?

**Comment by BallisticPain** [comment]
It seems this project has suffered the same fate as [twitter/typeahead.js](https://github.com/twitter/typeahead.js/issues/1320) (linked directly to the issue that created this fork).

I'm guessing it's inactive from the looks of things. I hate to see that, but I hate to just jump libraries for a few fixes ... Meh.

**Comment by rhysdavies1994** [comment]
+1 for release! Would like latest fixes for async results in release

**Comment by jonchay** [comment]
I agree what @BallisticPain said, it is indeed unfortunate..

I started using this [algolia/autocomplete](https://github.com/algolia/autocomplete.js) which is also forked from [twitter/typeahead](https://github.com/twitter/typeahead.js). 

Algolia is getting a lot of traction as a search engine and they're maintaining their typeahead library. Hope this helps!

**Comment by BallisticPain** [comment]
@jonchay Thanks for that link... so far I have swapped some of my typeahead functionality to using [select2](https://select2.github.io/) ... It has some nice features that make it a good choice for some of my controls, but I will definitely check the agolia version!

**Comment by jlbooker** [comment]
@corejavascript/collaborators  What do we need to do in order to get this release moving? We've fixed several things, and need to get them to the NPM and Bower registries. 

@lenovouser  Are you still around?

Who is the `mariusz-kraj` that owns the npm package?

**Comment by jorrit** [comment]
You can always raise an NPM naming dispute if the NPM package owner doesn't respond, see https://www.npmjs.com/policies/disputes.

**Comment by jlbooker** [comment]
@jorrit Yes, I wanted to ask around first though, in hopes of avoiding that. If I don't hear back from anyone soon, I'll reach out to the NPM support folks.

**Comment by MarkHerhold** [comment]
@jlbooker You should reach out to NPM immediately as people are likely downloading and using the module without knowing that a third party uploaded it (and therefore what is actually inside it). 

To be fair to the anonymous publisher, this project was terribly maintained after forking the twitter project and was missing a package for a very long time. I'm glad to see it's getting attention now.

**Comment by jlbooker** [comment]
@MarkHerhold I'm not too worried about there being unknown code in the package that's currently in the NPM registry. I'm using the corejs-typeahead package for internal projects and I've looked through the code. It appears to be a legitimate copy.

I emailed the current package owner on 25 Oct. I'll wait until 31 Oct for a reply before reaching out to NPM support.

**Comment by jlbooker** [comment]
I've contacted NPM support and started the process for disputing the package name. The NPM [policy docs](https://docs.npmjs.com/policies/disputes) say this can take up to 4 weeks....

**Comment by jlbooker** [comment]
Good news everyone.. The package owner responded and agreed to turn the NPM package ownership over to me. So, we resolved the ownership issue amicably and avoided the month-long wait.

The NPM support folks have asked us to release the next version as 1.0.0. I'm not completely excited about that, since a "version 1.0.0" carries some other connotations (stable, complete, "ready", etc). However, I understand why they're asking for it. Under the semver rules, a 1.0.0 release (i.e. the next major version number) will create a clean break indicating non-backwards compatibility. This will prevent npm clients from automatically updating packages (in most cases). Projects that use this package will have to specifically update the package.json file in order to get the next version of this package. Because the ownership is changing, that behavior makes some sense.

I'm going to update this issue's title and the milestone to reflect the 1.0 version. I'm going to start putting together a 1.0 release candidate. My goal is to have a beta version available for testing by the end of the week (if my other primary-job-related projects cooperate).

**Comment by jlbooker** [comment]
More good news... v1.0.1 was released last week! See: https://github.com/corejavascript/typeahead.js/releases/tag/v1.0.1

And on NPM at: https://www.npmjs.com/package/corejs-typeahead

Closing!
